[package]
name = "maniparse"
version = "0.2.0"
authors = ["Jonathan Gerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features=["derive" ]}
serde_yaml = "0.8"
anyhow = "1.0"
itertools = "0.9.0"
mustache="0.9"
